![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/68501079-0695df00-023c-11ea-841f-455dac84a089.jpg"
    style="width:400px; float: right; margin: 0 40px 40px 40px;"></img>

# Reading HTML tables

In this lecture we'll learn how to read and parse HTML tables from websites into a list of `DataFrame` objects to work with.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [1]:
!pip install lxml

Collecting lxml
  Downloading lxml-4.7.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 1.9 MB/s eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-4.7.1

In [1]:
import pandas as pd

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Parsing raw HTML strings

Another useful pandas method is `read_html()`. This method will read HTML tables from a given URL, a file-like object, or a raw string containing HTML, and return a list of `DataFrame` objects.

Let's try to read the following `html_string` into a `DataFrame`.

In [2]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [3]:
dfs = pd.read_html(html_string)

The `read_html` just returned one `DataFrame` object:

In [4]:
len(dfs)

1

In [5]:
dfs

[  Order date   Region    Item  Units  Unit cost
 0   1/6/2018     East  Pencil     95       1.99
 1  1/23/2018  Central  Binder     50      19.99
 2   2/9/2018  Central  Pencil     36       4.99
 3  3/15/2018     West     Pen     27      19.99]

In [6]:
df = dfs[0]

df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

Previous `DataFrame` looks quite similar to the raw HTML table, but now we have a `DataFrame` object, so we can apply any pandas operation we want to it.

In [7]:
df.shape

(4, 5)

In [8]:
df.loc[df['Region'] == 'Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [9]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

### Defining header

Pandas will automatically find the header to use thanks to the <thead> tag.
    
But in many cases we'll find wrong or incomplete tables that make the `read_html` method parse the tables in a wrong way without the proper headers.

To fix them we can use the `header` parameter.

In [10]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td> 
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td> 
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td> 
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td> 
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td> 
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [15]:
pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In this case, we'll need to pass the row number to use as header using the `header` parameter.

In [16]:
pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Parsing HTML tables from the web

Now that we know how `read_html` works, go one step beyond and try to parse HTML tables directly from an URL.

To do that we'll call the `read_html` method with an URL as paramter.

### Simple example

In [11]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [12]:
nba_tables = pd.read_html(html_url)

In [13]:
len(nba_tables)

1

We'll work with the only one table found:

In [14]:
nba_tables

[      Rk        Player Pos Age   Tm   G  GS    MP   FG   FGA  ...   FT%  ORB  \
 0      1  Álex Abrines  SG  25  OKC  31   2  19.0  1.8   5.1  ...  .923  0.2
 1      2    Quincy Acy  PF  28  PHO  10   0  12.3  0.4   1.8  ...  .700  0.3
 2      3  Jaylen Adams  PG  22  ATL  34   1  12.6  1.1   3.2  ...  .778  0.3
 3      4  Steven Adams   C  25  OKC  80  80  33.4  6.0  10.1  ...  .500  4.9
 4      5   Bam Adebayo   C  21  MIA  82  28  23.3  3.4   5.9  ...  .735  2.0
 ..   ...           ...  ..  ..  ...  ..  ..   ...  ...   ...  ...   ...  ...
 729  528  Tyler Zeller   C  29  MEM   4   1  20.5  4.0   7.0  ...  .778  2.3
 730  529    Ante Žižić   C  22  CLE  59  25  18.3  3.1   5.6  ...  .705  1.8
 731  530   Ivica Zubac   C  21  TOT  59  37  17.6  3.6   6.4  ...  .802  1.9
 732  530   Ivica Zubac   C  21  LAL  33  12  15.6  3.4   5.8  ...  .864  1.6
 733  530   Ivica Zubac   C  21  LAC  26  25  20.2  3.8   7.2  ...  .733  2.3

      DRB  TRB  AST  STL  BLK  TOV   PF   PTS
 0    1.4  1.5  0.6  0.5  0.2  0.5  1.7   5.3
 1    2.2  2.5  0.8  0.1  0.4  0.4  2.4   1.7
 2    1.4  1.8  1.9  0.4  0.1  0.8  1.3   3.2
 3    4.6  9.5  1.6  1.5  1.0  1.7  2.6  13.9
 4    5.3  7.3  2.2  0.9  0.8  1.5  2.5   8.9
 ..   ...  ...  ...  ...  ...  ...  ...   ...
 729  2.3  4.5  0.8  0.3  0.8  1.0  4.0  11.5
 730  3.6  5.4  0.9  0.2  0.4  1.0  1.9   7.8
 731  4.2  6.1  1.1  0.2  0.9  1.2  2.3   8.9
 732  3.3  4.9  0.8  0.1  0.8  1.0  2.2   8.5
 733  5.3  7.7  1.5  0.4  0.9  1.4  2.5   9.4

 [734 rows x 30 columns]]

In [15]:
nba = nba_tables[0]

In [46]:
nba.head(25)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7

In [57]:
# nba.drop(range(22, nba.shape[0] + 1, 20))

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [66]:
nba.drop(nba[nba['Rk'] == 'Rk'].index)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [67]:
nba.head(50)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7
25,23,Trevor Ariza,SF,33,TOT,69,69,34.0,4.3,10.7,...,.793,0.7,4.7,5.4,3.7,1.3,0.3,1.5,1.9,12.5
26,23,Trevor Ariza,SF,33,PHO,26,26,34.0,3.3,8.7,...,.837,0.6,5.0,5.6,3.3,1.5,0.3,1.5,1.7,9.9
27,23,Trevor Ariza,SF,33,WAS,43,43,34.1,4.8,11.8,...,.777,0.8,4.5,5.3,3.8,1.2,0.3,1.6,2.0,14.1
28,24,D.J. Augustin,PG,31,ORL,81,81,28.0,3.9,8.4,...,.866,0.5,2.0,2.5,5.3,0.6,0.0,1.6,1.4,11.7
29,25,Deandre Ayton,C,20,PHO,71,70,30.7,7.2,12.3,...,.746,3.1,7.1,10.3,1.8,0.9,0.9,1.8,2.9,16.3
30,26,Dwayne Bacon,SG,23,CHO,43,13,17.7,2.8,6.0,...,.739,0.2,1.9,2.1,1.1,0.3,0.1,0.4,1.7,7.3
31,27,Marvin Bagley III,PF,19,SAC,62,4,25.3,5.7,11.4,...,.691,2.6,5.0,7.6,1.0,0.5,1.0,1.6,1.9,14.9
32,28,Ron Baker,SG,25,TOT,15,0,10.1,0.3,1.3,...,.833,0.1,0.7,0.7,1.0,0.4,0.1,0.3,1.2,0.9
33,28,Ron Baker,SG,25,NYK,11,0,9.7,0.4,1.5,...,.833,0.1,0.5,0.6,1.2,0.5,0.0,0.3,1.5,1.3
34,28,Ron Baker,SG,25,WAS,4,0,11.3,0.0,1.0,...,NaN,0.0,1.0,1.0,0.5,0.3,0.3,0.5,0.5,0.0
35,29,Wade Baldwin,PG,22,POR,16,0,5.9,0.6,2.1,...,.727,0.1,0.8,0.9,0.8,0.1,0.1,0.9,0.7,1.9
36,30,Lonzo Ball,PG,21,LAL,47,45,30.3,3.9,9.7,...,.417,1.1,4.2,5.3,5.4,1.5,0.4,2.2,2.4,9.9
37,31,Mo Bamba,C,20,ORL,47,1,16.3,2.5,5.2,...,.587,1.4,3.6,5.0,0.8,0.3,1.4,0.9,2.2,6.2
38,32,J.J. Barea,PG,34,DAL,38,0,19.8,4.2,10.1,...,.705,0.3,2.2,2.5,5.6,0.6,0.0,1.9,1.3,10.9
39,33,Harrison Barnes,PF-SF,26,TOT,77,77,32.9,5.6,13.3,...,.824,0.7,3.9,4.7,1.5,0.6,0.2,1.3,1.6,16.4
40,33,Harrison Barnes,PF,26,DAL,49,49,32.3,5.9,14.6,...,.833,0.7,3.5,4.2,1.3,0.7,0.2,1.4,1.6,17.7
41,33,Harrison Barnes,SF,26,SAC,28,28,33.9,5.0,11.1,...,.800,0.8,4.8,5.5,1.9,0.6,0.1,1.1,1.5,14.3
42,34,Will Barton,SF,28,DEN,43,38,27.7,4.3,10.7,...,.770,0.7,3.9,4.6,2.9,0.4,0.5,1.5,1.9,11.5
43,35,Keita Bates-Diop,SF,23,MIN,30,3,16.8,2.0,4.7,...,.643,0.5,2.2,2.8,0.6,0.6,0.5,0.5,1.0,5.0
44,36,Nicolas Batum,SF,30,CHO,75,72,31.4,3.4,7.5,...,.865,0.9,4.3,5.2,3.3,0.9,0.6,1.6,1.9,9.3
45,37,Jerryd Bayless,PG,30,MIN,34,6,19.3,2.4,6.8,...,.571,0.3,1.5,1.8,3.5,0.5,0.1,0.9,1.6,6.1
46,38,Aron Baynes,C,32,BOS,51,18,16.1,2.1,4.4,...,.855,1.7,3.0,4.7,1.1,0.2,0.7,0.8,2.5,5.6
47,39,Kent Bazemore,SG,29,ATL,67,35,24.5,4.1,10.3,...,.726,0.6,3.3,3.9,2.3,1.3,0.6,1.8,2.5,11.6
48,40,Bradley Beal,SG,25,WAS,82,82,36.9,9.3,19.6,...,.808,1.1,3.9,5.0,5.5,1.5,0.7,2.7,2.8,25.6
50,41,Malik Beasley,SG,22,DEN,81,18,23.2,4.3,9.1,...,.848,0.4,2.0,2.5,1.2,0.7,0.1,0.7,1.4,11.3
51,42,Michael Beasley,PF,30,LAL,26,2,10.7,2.9,5.9,...,.718,0.5,1.8,2.3,1.0,0.3,0.4,1.0,1.6,7.0

### Complex example

We can also use the `requests` module to get HTML code from an URL to parse it into `DataFrame` objects.

If we look at the given URL we can see multiple tables about The Simpsons TV show.

We want to keep the table with information about each season.

In [17]:
import requests

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

In [25]:
r = requests.get(html_url)

wiki_tables = pd.read_html(r.text, header=0)

In [23]:
len(wiki_tables)

41

In [28]:
wiki_tables[1].head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Most watched episode,Most watched episode
1,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Viewers(millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""

In [29]:
simpsons = wiki_tables[1]

In [30]:
simpsons.head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Most watched episode,Most watched episode
1,Season,Season,No. ofepisodes,Season premiere,Season finale,Time slot (ET),Avg. viewers(in millions),Viewers(millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""

Quick clean on the table: remove extra header rows and set `Season` as index.

In [32]:
simpsons.drop([0, 1], inplace=True)

KeyError: '[0 1] not found in axis'

In [34]:
simpsons.head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
5,4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
6,5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""

In [35]:
simpsons.set_index('Season', inplace=True)

In [39]:
simpsons

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""
6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,15.6,22.2,"""Treehouse of Horror V"""
7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24)Sunday 8:30 pm (...,15.1,19.7,"""Treehouse of Horror VI"""
8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3)Sunday 8:00 pm (E...,14.5,20.9,"""The Springfield Files"""
9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,15.3,19.8,"""The Two Mrs. Nahasapeemapetilons"""
10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,13.5,15.5,"""Maximum Homerdrive"""
11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.8,18.4,"""The Mansion Family"""
12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,15.5,18.6,"""Worst Episode Ever"""
13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1)Sunday 8:00 pm (Epi...,12.5,14.9,"""The Parent Rap"""
14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21)Sunday 8:...",14.4,22.1,"""I'm Spelling as Fast as I Can"""
15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,11.0,16.3,"""I, (Annoyed Grunt)-Bot"""
16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20)Sun...",10.2,23.07,"""Homer and Ned's Hail Mary Pass"""
17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.55,11.63,"""Treehouse of Horror XVI"""
18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,9.15,13.90,"""The Wife Aquatic"""
19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8.37,11.7,"""Treehouse of Horror XVIII"""
20,2008–09,21,"September 28, 2008","May 17, 2009",Sunday 8:00 pm,7.1,12.4,"""Treehouse of Horror XIX"""
21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.1,14.62,"""Once Upon a Time in Springfield"""
22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.09,12.6,"""Moms I'd Like to Forget"""
23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,6.15[147],11.48,"""The D'oh-cial Network"""
24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1-21)Sunday 8:30 pm (...,5.41[148],8.97,"""Homer Goes to Prep School"""
25,2013–14,22,"September 29, 2013","May 18, 2014",Sunday 8:00 pm (Episodes 1–11 & 13-22)Sunday 7...,5.02[149],12.04,"""Steal This Episode"""
26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.61[150],10.62,"""The Man Who Came to Be Dinner"""
27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.0[151],8.33,"""Teenage Mutant Milk-Caused Hurdles"""
28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.80[152],8.19,"""Pork and Burns"""
29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.07[153],8.04,"""Frink Gets Testy"""
30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.10[154],8.20,"""The Girl on the Bus"""
31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,2.58[155],5.63,"""Go Big or Go Homer"""
32,2020–21,22,"September 27, 2020","May 23, 2021",Sunday 8:00 pm (Episodes 1–10 & 12-22)Sunday 9...,2.32[156],4.93,"""Treehouse of Horror XXXI"""
33,2021–22,22,"September 26, 2021","May 15, 2022[157]",Sunday 8:00 pm (Episodes 1–10 & 12-22)Sunday 9...,TBA,TBA,TBA

Which season has the lowest number of episodes?

In [38]:
simpsons['No. ofepisodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20'], dtype=object)

In [40]:
simpsons = simpsons.loc[simpsons['No. ofepisodes'] != 'TBA']
simpsons

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""
6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,15.6,22.2,"""Treehouse of Horror V"""
7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24)Sunday 8:30 pm (...,15.1,19.7,"""Treehouse of Horror VI"""
8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3)Sunday 8:00 pm (E...,14.5,20.9,"""The Springfield Files"""
9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,15.3,19.8,"""The Two Mrs. Nahasapeemapetilons"""
10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,13.5,15.5,"""Maximum Homerdrive"""
11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.8,18.4,"""The Mansion Family"""
12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,15.5,18.6,"""Worst Episode Ever"""
13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1)Sunday 8:00 pm (Epi...,12.5,14.9,"""The Parent Rap"""
14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21)Sunday 8:...",14.4,22.1,"""I'm Spelling as Fast as I Can"""
15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,11.0,16.3,"""I, (Annoyed Grunt)-Bot"""
16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20)Sun...",10.2,23.07,"""Homer and Ned's Hail Mary Pass"""
17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.55,11.63,"""Treehouse of Horror XVI"""
18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,9.15,13.90,"""The Wife Aquatic"""
19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8.37,11.7,"""Treehouse of Horror XVIII"""
20,2008–09,21,"September 28, 2008","May 17, 2009",Sunday 8:00 pm,7.1,12.4,"""Treehouse of Horror XIX"""
21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.1,14.62,"""Once Upon a Time in Springfield"""
22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.09,12.6,"""Moms I'd Like to Forget"""
23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,6.15[147],11.48,"""The D'oh-cial Network"""
24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1-21)Sunday 8:30 pm (...,5.41[148],8.97,"""Homer Goes to Prep School"""
25,2013–14,22,"September 29, 2013","May 18, 2014",Sunday 8:00 pm (Episodes 1–11 & 13-22)Sunday 7...,5.02[149],12.04,"""Steal This Episode"""
26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.61[150],10.62,"""The Man Who Came to Be Dinner"""
27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.0[151],8.33,"""Teenage Mutant Milk-Caused Hurdles"""
28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.80[152],8.19,"""Pork and Burns"""
29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.07[153],8.04,"""Frink Gets Testy"""
30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.10[154],8.20,"""The Girl on the Bus"""
31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,2.58[155],5.63,"""Go Big or Go Homer"""
32,2020–21,22,"September 27, 2020","May 23, 2021",Sunday 8:00 pm (Episodes 1–10 & 12-22)Sunday 9...,2.32[156],4.93,"""Treehouse of Horror XXXI"""
33,2021–22,22,"September 26, 2021","May 15, 2022[157]",Sunday 8:00 pm (Episodes 1–10 & 12-22)Sunday 9...,TBA,TBA,TBA

In [41]:
min_season = simpsons['No. ofepisodes'].min()

min_season

'13'

In [42]:
simpsons.loc[simpsons['No. ofepisodes'] == min_season]

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Save to CSV file

Finally save the `DataFrame` to a CSV file as we saw on previous lectures.

In [43]:
simpsons.head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""

In [44]:
simpsons.to_csv('out.csv')

In [45]:
pd.read_csv('out.csv', index_col='Season').head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an 'F'"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,18.9,24.0,"""Treehouse of Horror IV"""

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)